> Many bug-fixes and new GUI components hscroll and vscroll > New LU-Matrix decomposition for DynMatrix instances
Bug fixes:
* fixed documentation in SwissRanger class
* fixed bug, that GUI widget's Menu could not
  be created before painit(...) was called
* fixed bug, that the generic grabber did not
  set it's type property in case of using a 
  SwissRangerGrabber internally
* fixed bug in camcfg, that caused that it was
  not possible to configure SwissRanger devices only
* fixed installation prefix for scripts/icl-make
  which was placed in prefix/bin instead of
  prefix/bin/icl-VERSION/
* adapted icl-make to use new pkg-config file
  name for icl (something like icl-5.6.0-debug.pc)

New Script:
* Added shell script icl-version, that simply 
  prints the current icl-version 

New GUI components:
* introduced two new GUI-container components
  hscroll is a scroll widget, that contains a hbox
  and therefore also serves as horizontally aligned
  container
* also introduce vscroll (which behaves analog to 
  hscroll, but uses a vertically aligned layout)
* generalized the BoxHandle class, which is now able
  to represent hbox and vbox as well as hscroll and
  vscroll
* adapted icl-gui-test to use one of these new
  scroll components

LU-Decomposition:
* Added decompose_LU to DynMatrix class that implements 
  LU decomposition without partial pivoting
* added solve()-method to DynMatrix class, that can be used
  to solve Ax=b using one of the methods LU-decomposition,
  matrix-inverse, QR-decomposition based pseudo-inverse and
  SVD-based speudo-inverse
* added benchmarks for the solve-function documentation
  result: LU-decomposition is very fast, but less accurate
  than the other methods. For small matrices (like 4x4 up to 6x6)
  it is strongly recommended to use the "inv" method that solves
  Ax=b by x=inv(A)b. For small matrices this is faster and
  much more accurate!

diff --git a/scripts/icl-make b/scripts/icl-make
--- a/scripts/icl-make
+++ b/scripts/icl-make
@@ -1,3 +1,5 @@
+ICL_PC=@ICL_PGK_CFG_PLACEHOLDER@
+
 if [ ! "$1" ] ; then
     echo "$1 is the compilation target e.g. test for compiling test.cpp" ;
     exit -1 ;
@@ -5,13 +7,13 @@ fi
 
 if [ "$1" = "--help" ] ; then
     echo "icl-make applies the following command:" ;
-    echo 'CXXFLAGS="$CXXFLAGS $(pkg-config --cflags icl) -I." LDFLAGS="$LDFLAGS $(pkg-config --libs icl)" make $1' ;
+    echo 'CXXFLAGS="$CXXFLAGS $(pkg-config --cflags ${ICL_PC}) -I." LDFLAGS="$LDFLAGS $(pkg-config --libs ${ICL_PC})" make $1' ;
     exit 0 ;
 fi
 
-if [ "`pkg-config --exists icl && echo yes || echo no`" == "no" ] ; then
-    echo "icl.pc could not be found in your PKG_CONFIG_PATH" ;
+if [ "`pkg-config --exists ${ICL_PC} && echo yes || echo no`" == "no" ] ; then
+    echo "${ICL_PC}.pc could not be found in your PKG_CONFIG_PATH" ;
     exit -1 ;
 fi
 
-CXXFLAGS="$CXXFLAGS $(pkg-config --cflags icl) -I." LDFLAGS="$LDFLAGS $(pkg-config --libs icl)" make $1
+CXXFLAGS="$CXXFLAGS $(pkg-config --cflags ${ICL_PC}) -I." LDFLAGS="$LDFLAGS $(pkg-config --libs ${ICL_PC})" make $1
